config/routes.rb
Rails.application.routes.draw do
  get 'promos/dashboard' => 'promos#dashboard'
  get 'promos/user_promos' => 'promos#user_promos'
  get 'promos/list' => 'promos#list'

  resources :promos

  devise_for :users, :controllers => {:registrations => "registrations"}

   devise_scope :user do
    get "/login" => "devise/sessions#new"
  end

  devise_scope :user do
    get "/logout" => "devise/sessions#destroy"
  end
  devise_scope :user do
    delete "/logout" => "devise/sessions#destroy"
  end

  root 'promos#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

         user ||= User.new # guest user (not logged in)
          if user.admin?
            can :manage, Promo
          else
            can :read, :all
          end
  end
end

app/models/promo.rb
class Promo < ActiveRecord::Base

	CATEGORIES = ['Electronics', 'Clothing', 'Food', 'Fitness','Hospitality']

	has_attached_file :image,
                    # :path =>  ":rails_root/public/system/:class/:attachment/:id_partition/:style/:filename",
                    :path => ":rails_root/public/images/:id/:style/:filename",
                    :url  => "/images/:id/:style/:filename",
                    :styles   => {
                    	:thumb    => ['200x200#',  :jpg, :quality => 70],
                    	:preview  => ['300x300#',  :jpg, :quality => 70],
                    	:large    => ['600>',      :jpg, :quality => 70],
                    	:retina   => ['1200>',     :jpg, :quality => 30]
                    }

                    validates :image, :attachment_presence => true
                    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
                    validates :description, :length => {minimum: 100}
                    validates_presence_of :discount, :category, :contact, :shop
     belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :promos

  
  def check_promo?
    self.promos.length > 0
  end
  
  def admin?
    self.role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    promos_dashboard_path
  end
end

app/controllers/promos_controller.rb
class PromosController < ApplicationController
  before_action :set_promo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:show, :index, :list]


  # GET /promos
  # GET /promos.json
  def index
    @promos = Promo.all
  end

  def list

    if params[:location] == ""
      location = "accra"
    @promos = Promo.where("product LIKE ? AND location LIKE ?", "%#{params[:product]}%", "%#{location}") 
    render 'list'
    else
       @promos = Promo.where("product LIKE ? AND location LIKE ?", "%#{params[:product]}%", "%#{params[:location]}%")
       render 'list'
    end
  end
  # GET /promos/1
  # GET /promos/1.json
  def show
  end

  def dashboard

  end
  def user_promos
    @promos = current_user.promos
  end
  # GET /promos/new
  def new
    @promo = Promo.new
  end

  # GET /promos/1/edit
  def edit
  end

  # POST /promos
  # POST /promos.json
  def create
    @promo = current_user.promos.create(promo_params)

    respond_to do |format|
      if @promo.save
        format.html { redirect_to action: 'index', notice: 'Promo was successfully created.' }
        format.json { render :show, status: :created, location: @promo }
      else
        format.html { render :new }
        format.json { render json: @promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promos/1
  # PATCH/PUT /promos/1.json
  def update
    respond_to do |format|
      if @promo.update(promo_params)
        format.html { redirect_to action: 'index', notice: 'Promo was successfully updated.' }
        format.json { render :show, status: :ok, location: @promo }
      else
        format.html { render :edit }
        format.json { render json: @promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promos/1
  # DELETE /promos/1.json
  def destroy
    @promo.destroy
    respond_to do |format|
      format.html { redirect_to promos_url, notice: 'Promo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promo
      @promo = Promo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def promo_params
      params.require(:promo).permit(:description, :product, :shop, :location, :contact, :picture, :discount, :normal_price, :category, :image, :user_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected
  def after_sign_up_path_for(resource)
    promos_dashboard_path
  end

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :role)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password, :role)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/promos_helper.rb
module PromosHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>EasyDiscount</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
   <%= stylesheet_link_tag 'mystyle' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body data-spy="scroll">
	<div class="container">
      <ul id="gn-menu" class="gn-menu-main">
        <li class="gn-trigger">
          <a class="gn-icon gn-icon-menu"><span>Menu</span></a>
          <nav class="gn-menu-wrapper">
            <div class="gn-scroller">
              <ul class="gn-menu">
                <li class="gn-search-item">
                  <!-- <input placeholder="Search" type="search" class="gn-search">
                  <a class="gn-icon gn-icon-search"><span>Search</span></a>
                </li> -->
                <li>
                  <a href="#about" class="gn-icon gn-icon-download">About</a>
                </li>
                <li>
                  <a href="#contact" class="gn-icon gn-icon-archive">Contact</a>
                </li>
                <li>
                      <% if user_signed_in? %>
                          <%= link_to logout_path, method: :delete do %>
                          <span class="sign-out-ico"> Logout</span>
                          <% end %>
                      <% else %>
                          <%= link_to login_path do %>
                            <span class="sign-in-ico"> Login</span>
                          <% end %>
                    <% end %>
                </li>
                <li>
                  <% if user_signed_in? %>
                          <%= link_to promos_dashboard_path do %>
                          <span class="dashboard-ico"> Dashboard Home</span>
                          <% end %>
                  <% end %>
                </li>
              </ul>
            </div><!-- /gn-scroller -->
          </nav>
        </li>
        <li><%= link_to 'EASYDISCOUNT', root_path %></li>
          <li>
                                <% if user_signed_in? %>
                                  <%= link_to logout_path, method: :delete do %>
                                  <span class="sign-out-ico"> Logout</span>
                                  <% end %>
                                <% else %>
                                  <%= link_to login_path do %>
                                    <span class="sign-in-ico"> Login</span>
                                  <% end %>
                            <% end %>
                          </li>
                          <li>
                              <% if user_signed_in? %>
                                 <%= link_to promos_dashboard_path do %>
                                  <span class="dashboard-ico"> Dashboard Home</span>
                              <% end %>
                              <% end %>
                          </li>
          <li>
              <a href="#about" class="gn-icon gn-icon-download">About</a>
          </li>
        <li><ul class="company-social">

                            <li class="social-facebook"><a href="#" target="_blank"><i class="fa fa-facebook"></i></a></li>
                            <li class="social-twitter"><a href="#" target="_blank"><i class="fa fa-twitter"></i></a></li>
                            <li class="social-dribble"><a href="#" target="_blank"><i class="fa fa-dribbble"></i></a></li>
                            <li class="social-google"><a href="#" target="_blank"><i class="fa fa-google-plus"></i></a></li>
                        </ul> </li>
      </ul>
  </div>

       <%= render 'layouts/messages' %>
  <div id="main-content">
       <%= yield %>
  </div>




<footer>
		<div class="container">
			<div class="row">
				<div class="col-md-12 col-lg-12">

					<p>Copyright &copy; 2014  <%= link_to 'EasyDiscount', root_path %></p>
				</div>
			</div>
		</div>
	</footer>
<script src="/assets/js/custom.js"></script>
</body>
</html>

app/views/promos/_form.html.erb
<div class="container">
  <div class="row">
          <%= bootstrap_form_for(@promo, layout: :horizontal, label_col: "col-sm-3 col-sm-offset-1", control_col: "col-sm-4") do |f| %>
          <% if @promo.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@promo.errors.count, "error") %> prohibited this promo from being saved:</h2>

            <ul>
              <% @promo.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          </div>
          <% end %>
          <%= f.text_field :shop %>
          <%= f.text_field :product %>
          <%= f.select :category, options_for_select(Promo::CATEGORIES, Promo::CATEGORIES ) %>
          <%= f.file_field :image %>
          <%= f.text_area :description %>
          <%= f.text_field :discount %>

          <%= f.number_field :normal_price %>
          <%= f.text_field :location %>
          <%= f.text_field :contact %>

          <div class="text-center form-btns">
            <%= f.submit :class => "btn btn-primary"%>
            <%= link_to 'Back', promos_path, :class => "btn btn-default btn-sm" %>
          </div>
          <% end %>
         
  </div>
  <div class="wrapper">
     <div class="span-4">
            <%= render 'side_info' %>
          </div>
  </div>
    
</div>

app/views/promos/_side_info.html.erb
 <div class="well">
    Remember to keep your discounts updated.
    You want to build credibility and integrity.
    Right?
    </div>

app/views/promos/dashboard.html.erb
<div class="jumbotron">
  <h1> 
      Welcome!
    </h1>
      
  <div class="row-fluid">
    <% if current_user.check_promo?%>  
    <div class="col-md-4">
      <%= link_to "View your current promos", promos_user_promos_path, :class => "btn btn-info" %>
    </div>
    <div class="col-md-4">
      <%= link_to "Create a new promo", new_promo_path, :class => "btn btn-success" %>
    </div>
    <div class="col-md-4">
      <%= link_to "Edit Registration Details", edit_user_registration_path, :class => "btn btn-danger" %>
    </div>
    <% else %>
      <h4>You don't have any promos yet</h4>
        <div class="col-md-4">
        <%= link_to "Create a new promo", new_promo_path, :class => "btn btn-success" %>
        </div>
        <div class="col-md-4">
        <%= link_to "Edit Registration Details", edit_user_registration_path, :class => "btn btn-danger" %>
        </div>
      <%end%>
  </div>
    
</div>




      

app/views/promos/edit.html.erb
<div class="container-fluid form_bg">
	<div class="row">
		<div class="col-md-6 col-md-offset-2" >
			<div>
				<h1>Editing promo</h1>

				<%= render 'form' %>
			</div>
		</div>
		<div class="col-md-4">
			<div class="side_form">
				Remember to keep your discounts updated.
				You want to build credibility and integrity.
				Right?
			</div>
		</div>
	</div>
</div>

app/views/promos/index.html.erb
    <!-- Section: intro -->
    <section id="intro" class="intro">
      <div class="slogan">
        <div class="header-bg">
        </div>
        <h1><strong>Easy Discounts</strong></h1>
        <div class="slogan-bg">
        </div>
        <p><h3><strong>Search for Promotions around you.</strong></h3></p>
        <!-- Implementation of search Bar -->

 <div class="container">
  <div class="row">
    <!-- <div class="col-md-10 col-md-offset-1 well myWell" style="border-radius:5px;"> -->
      <div class="well myWell" style="border-radius:5px;">
      </div>
        <div class="row">
          <div id="searchForm" class="col-md-12">
            <%= form_tag promos_list_path, method: :get do %>

              <div class="col-md-5 search">
                <div class="form-group" id="product_search">
                  <%= text_field_tag :product, params[:product], class: "form-control", placeholder: "Search a product", id: 'prod-search' %>
                </div>
              </div>

              <div class="col-md-5 search">
                <div class="form-group" id="product_search">
                <%= text_field_tag :location, params[:location], class: "form-control", placeholder: "Enter a location", id: 'loc-search' %>
              </div>
            </div>

              <div class="col-md-2 search">
                <span class="">
                <%= submit_tag 'GO!', class: "btn btn-default", id: 'submit-btn' %>
                </span>
              </div>
            <% end %>
          </div>
        <!-- </div> -->
      </div>
    </div>
  </div>
</div>

<!-- <div>
  <form id="custom-search-form" class="form-search form-horizontal pull-right">
      <div class="input-append span12">
          <input type="text" class="search-query mac-style" placeholder="Search">
          <button type="submit" class="btn"><i class="icon-search"></i></button>
      </div>
  </form>
</div> -->

<div align="center" id="lead-btn">
<%= link_to "Check All Discounts", promos_list_path, class: "btn btn-primary" %>
</div>

</section>
<!-- /Section: intro -->


<div class="container top1">
  <div class="row">
    <% @promos.reverse[0..2].each do |promo| %>

    <div class="col-md-4">
      <div class="card">
        <!-- <div class=" card-image waves-effect waves-block waves-light">

          <%#= image_tag promo.image, class: "activator" %>

        </div> -->
         <div class="">
          <%= image_tag promo.image(:preview) %>
        </div>

        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4"><%= promo.product %><i class="fa fa-ellipsis-v repairI"></i></span>
          <br>
          <%= promo.shop %>
          <br>
          <%= promo.location %>
          <br>
          <div align="right">
           <div id="discount-rate"><span><%= promo.discount %> %&nbsp;</span>Off</div>
           <br>
           <%= promo.normal_price %>
         </div>


       </div>
       <div class="card-reveal">
        <span class="card-title grey-text text-darken-4"><%= promo.product %> <i class="fa fa-times repairI"></i></span>
        <br>
        <p><%= promo.description %></p>
        <h4>Contact</h4>
        <%= promo.contact %>
        <br>
        <br>
        <div align="center">
          <% if can? :update, promo %>
              <%= link_to 'Delete',
              promo_path(promo),
              :method => :delete,
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-xs btn-danger' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <% end %>

  <br>
</div>

<%#= link_to 'New Promo', new_promo_path %>
</div>




<!-- Section: about -->
    <section id="about" class="home-section text-center bg-gray">
    <div class="heading-about marginbot-50">
      <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2">

          <div class="section-heading">
          <h2>About us</h2>
          <p>Stop the hustle of going from shop to shop doing window shopping, asking for prices to items that you need. Do this with EasyDiscount. We bring you the best price deals out there!!.</p>
          </div>

        </div>
      </div>
      </div>
    </div>
    <div class="container">

        <div class="row">
            <div class="col-xs-4 col-sm-2 col-md-2">

                <div class="team boxed-grey">
                    <div class="inner">
            <h5>Laud Bruce</h5>
                        <p class="subtitle">Backend (RoR)</p>
                        <div class="avatar"><%= image_tag("Laud.jpeg", :alt => "Kwame", class: "pics" )%></div>
                    </div>
                </div>

            </div>
      <div class="col-xs-8 col-sm-2 col-md-2">

                <div class="team boxed-grey">
                    <div class="inner">
            <h5>Innocent Udeogu</h5>
                        <p class="subtitle">Backend (RoR)</p>
                        <div class="avatar"><%= image_tag("Innocent.JPG", :alt => "Kwame", class: "pics" )%></div>
                    </div>

        </div>
            </div>
      <div class="col-xs-8 col-sm-2 col-md-2">

                <div class="team boxed-grey">
                    <div class="inner">
            <h5>John Bordebo</h5>
                        <p class="subtitle">Research</p>
                        <div class="avatar"><%= image_tag("John.jpg", :alt => "Kwame", class: "pics" )%></div>
                    </div>
                </div>

            </div>
      <div class="col-xs-8 col-sm-2 col-md-2">

                <div class="team boxed-grey">
                    <div class="inner">
            <h5>Kennedy Anyinatoe</h5>
                        <p class="subtitle">UI / UX</p>
                        <div class="avatar"><%= image_tag("Kennedy.jpg", :alt => "Kwame", class: "pics" )%></div>
                    </div>
                </div>

            </div>
      

       <div class="col-xs-8 col-sm-2 col-md-2">

                <div class="team boxed-grey">
                    <div class="inner">
            <h5>Asiedu Amoako Kwame</h5>
                        <p class="subtitle">UI / UX</p>
                        <div class="avatar"><%= image_tag("Kwame.jpg", :alt => "Kwame", class: "pics" )%></div>
                    </div>
                </div>

            </div>


        </div>
    </div>
  </section>
  <!-- /Section: about -->

app/views/promos/list.html.erb
<div class="container top">

  <div class="row">
    <% if @promos.empty? %>
   <div class="col-sm-8 col-sm-offset-2"><h2>OOOPS! there are no discounts. Please try another search.</h2></div>
    <% else %>
    <% @promos.reverse.each do |promo| %>
    <div class="col-md-4">
      <div class="card">
        <!-- <div class="card-image waves-effect waves-block waves-light">

          <%#= image_tag promo.image, class: "activator"%>

        </div> -->
        <div class="">
          <%= image_tag promo.image(:preview) %>
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4"><%= promo.product %><i class="fa fa-ellipsis-v repairI"></i></span>
          <br>
          <%= promo.shop %>
          <br>
          <%= promo.location %>
          <br>
          <div align="right">
           <div id="discount-rate"><span><%= promo.discount %> %&nbsp;</span>Off</div>
           <br>
           <%= promo.normal_price %>
         </div>
         

       </div>
       <div class="card-reveal">
        <span class="card-title grey-text text-darken-4"><%= promo.product %> <i class="fa fa-times repairI"></i></span>
        <br>
        <p><%= promo.description %></p>
        <h5>Contact</h5>
        <%= promo.contact %>
        <!-- <div id="loc-value">
          <%#= promo.location %>
        </div> -->

        <%#= link_to (image_tag('marker.png', size: '40x40')), '#mapmodals', 'data-toggle' => 'modal' %>
        <br>
        <br>
        <div align="center">
           <%# if can? :update, promo %> 
              <%= link_to 'Delete',
              promo_path(promo),
              :method => :delete,
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-xs btn-danger' %>
            <%# end %>
        </div>
      </div>
    </div>
  </div>
  <% end %>

  <br>
  <% end %>
</div>
</div>

app/views/promos/new.html.erb
<h2 class="text-center">Create your new Promo</h2>
	
		<%= render 'form' %>
   

app/views/promos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @promo.description %>
</p>

<p>
  <strong>Product:</strong>
  <%= @promo.product %>
</p>

<p>
  <strong>Shop:</strong>
  <%= @promo.shop %>
</p>

<p>
  <strong>Location:</strong>
  <%= @promo.location %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag @promo.image(:preview) %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @promo.discount %>
</p>

<p>
  <strong>Normal price:</strong>
  <%= @promo.normal_price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @promo.category %>
</p>

<%= link_to 'Edit', edit_promo_path(@promo) %> |
<%= link_to 'Back', promos_path %>

app/views/promos/user_promos.html.erb
<div class="container">

  <div class="row">
    <% @promos.each do |promo| %>
    <div class="col-md-4">
      <div class="card">
        <div class="card-image waves-effect waves-block waves-light">

          <%= image_tag("box.jpg", class: "activator")%>

        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4"><%= promo.product %><i class="fa fa-ellipsis-v repairI"></i></span>
          <br>
          <%= promo.shop %>
          <br>
          <%= promo.location %>
          <br>
          <div align="right">
           <span> <%= promo.discount %> %</span>
           <br>
           <%= promo.normal_price %>
         </div>
         

       </div>
       <div class="card-reveal">
        <span class="card-title grey-text text-darken-4"><%= promo.product %> <i class="fa fa-times repairI"></i></span>
        <br>
        <p><%= promo.description %></p>
        <h5>Contact</h5>
        <%= promo.contact %>
        <!-- <div id="loc-value">
          <%#= promo.location %>
        </div> -->

        <%#= link_to (image_tag('marker.png', size: '40x40')), '#mapmodals', 'data-toggle' => 'modal' %>
        <br>
        <br>
        <div align="center">
           <% if can? :update, promo %> 
              <%= link_to 'Delete',
              promo_path(promo),
              :method => :delete,
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-xs btn-danger' %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
  <% end %>

  <br>

</div>
<div class="new-promo">
   <%= link_to 'New Promo', new_promo_path, class: 'btn btn-primary' %>
</div>

</div>